project:
  type: website

website:
  title: "Reed Crocker"
  description: "A curious programmer, scientist, and data professional."
  favicon: assets/favicon/favicon-32x32.png
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: 'Experience'
        href: experience.qmd
      - text: 'Projects'
        href: projects.qmd
      - text: 'Contact'
        href: contact.qmd
  page-footer:  
    left: >-
     &#169; 2024 Reed Crocker &#8729; Made with [Quarto](https://quarto.org)

format:
  html:
    theme:
      dark: assets/styles/reed-dark.scss
      light: assets/styles/reed-light.scss
    toc: true



